# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
