# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Weblog',
        ),
    ]
