# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='blog_id',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='blog_num',
        ),
    ]
