# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170715_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='blog_title',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
