# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_weblog_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='blog_title',
            field=models.CharField(default='title', max_length=1000),
            preserve_default=False,
        ),
    ]
